import { COMPARISON_REFERENCES, PUBLIC_CASES } from "../methodology.mjs";
import { color } from "../reporting.mjs";
import { localized } from "../shared.mjs";

const GOOGLE_SOURCE_URL = PUBLIC_CASES.googleRequest.sourceUrl;
const OPENAI_SOURCE_URL = PUBLIC_CASES.openaiRequest.sourceUrl;
const MISTRAL_SOURCE_URL = PUBLIC_CASES.mistralLifecycle.sourceUrl;
const WATERSENSE_SOURCE_URL = COMPARISON_REFERENCES.waterSense.sourceUrl;
const DISHWASHER_SOURCE_URL = COMPARISON_REFERENCES.energyStarDishwasher.sourceUrl;
const EPA_EQUIVALENCIES_SOURCE_URL = COMPARISON_REFERENCES.epaEquivalencies.sourceUrl;

function focusedExplain(topic, lang = "zh") {
  const sections = {
    resources: {
      zh: [
        color("1;31", "资源估算 · 公开高位参照"),
        "",
        "这些值不是实际测量，也不是统计置信区间。",
        "不同厂商案例分别计算，主账单只展示数值最高的具名案例，不把口径拼成范围。",
        "",
        color("1", "Google · 请求级生产测量"),
        "  0.24 Wh · 0.26 mL 水 · 0.03 gCO₂e / 中位文本请求",
        "  包含活跃加速器、主机、空闲容量和数据中心开销。",
        `  ${GOOGLE_SOURCE_URL}`,
        "",
        color("1", "OpenAI · 请求级公开平均"),
        "  0.34 Wh · 0.32176 mL 水 / 平均 ChatGPT 查询",
        "  未公开模型、请求长度和完整测量边界。",
        `  ${OPENAI_SOURCE_URL}`,
        "",
        color("1", "Mistral · 生命周期高位"),
        "  400 输出 tokens · 45 mL 水 · 1.14 gCO₂e",
        "  包含服务器制造等上游影响，不包含用户终端。",
        `  ${MISTRAL_SOURCE_URL}`,
        "",
        "选择逻辑：",
        "  电力 = max(请求数 × Google 0.24, 请求数 × OpenAI 0.34)",
        "  水耗 = max(请求级案例, 输出 tokens ÷ 400 × Mistral 45)",
        "  碳排 = max(请求数 × Google 0.03, 输出 tokens ÷ 400 × Mistral 1.14)",
        "",
      ],
      en: [
        color("1;31", "RESOURCE ESTIMATE · NAMED PUBLIC HIGH-SIDE REFERENCE"),
        "",
        "These values are neither measurements nor statistical confidence intervals.",
        "Each vendor case is calculated separately; the receipt shows the highest named case.",
        "",
        color("1", "Google · request-level production measurement"),
        "  0.24 Wh · 0.26 mL water · 0.03 gCO₂e / median text prompt",
        "  Includes active accelerators, hosts, idle capacity, and data-center overhead.",
        `  ${GOOGLE_SOURCE_URL}`,
        "",
        color("1", "OpenAI · published request-level average"),
        "  0.34 Wh · 0.32176 mL water / average ChatGPT query",
        "  Model, request length, and full measurement boundary were not published.",
        `  ${OPENAI_SOURCE_URL}`,
        "",
        color("1", "Mistral · lifecycle high-side case"),
        "  400 output tokens · 45 mL water · 1.14 gCO₂e",
        "  Includes upstream server manufacturing and excludes user devices.",
        `  ${MISTRAL_SOURCE_URL}`,
        "",
        "Selection:",
        "  Energy = max(requests × Google 0.24, requests × OpenAI 0.34)",
        "  Water = max(request cases, output tokens ÷ 400 × Mistral 45)",
        "  Carbon = max(requests × Google 0.03, output tokens ÷ 400 × Mistral 1.14)",
        "",
      ],
    },
    comparisons: {
      zh: [
        color("1;31", "生活翻译 · 展示假设"),
        "",
        "today · 小事务（每次 5 条）",
        "  10W LED 灯 · 19Wh 手机充电 · 550mL 饮用水 · 0.05mL 一滴水 · 平均燃油车",
        "",
        "week · 中事务（每次 5 条）",
        "  烧开 1L 水约 100Wh · 50W 笔记本 · 1kW 微波炉",
        "  7.6L/min WaterSense 淋浴 · 12.1L ENERGY STAR 洗碗机",
        "",
        "month · 大事务（每次 5 条）",
        "  244.2 gCO₂e/km 平均燃油车 · 60kgCO₂/年城市树",
        "  2.5ML 标准泳池 · 33.4kWh 美国家庭日均用电 · 150L 一缸洗澡水",
        "",
        "不足 0.01 次的大事务显示“还差多少倍”，不会舍入成 0.00。",
        "LED、手机、饮用水、烧水、电脑、微波炉、泳池和浴缸采用透明的整值展示假设。",
        "",
        "官方换算参照：",
        "  EPA WaterSense：2.0 gal/min ≈ 7.6L/min",
        `  ${WATERSENSE_SOURCE_URL}`,
        "  ENERGY STAR 标准洗碗机：3.2 gal/cycle ≈ 12.1L/cycle",
        `  ${DISHWASHER_SOURCE_URL}`,
        "  EPA 平均燃油车：3.93×10⁻⁴ metric ton CO₂e/mile ≈ 244.2g/km",
        "  EPA 城市树：0.060 metric ton CO₂/year",
        "  EPA 美国家庭用电：12,194kWh/year ≈ 33.4kWh/day",
        `  ${EPA_EQUIVALENCIES_SOURCE_URL}`,
        "",
      ],
      en: [
        color("1;31", "EVERYDAY TRANSLATION · DISPLAY ASSUMPTIONS"),
        "",
        "today · small activities (five each time)",
        "  10W LED · 19Wh phone charge · 550mL drinking water · 0.05mL drop · gas car",
        "",
        "week · medium activities (five each time)",
        "  Boil 1L water at about 100Wh · 50W laptop · 1kW microwave",
        "  7.6L/min WaterSense shower · 12.1L ENERGY STAR dishwasher",
        "",
        "month · large activities (five each time)",
        "  Gas car at 244.2 gCO₂e/km · urban tree at 60kgCO₂/year",
        "  2.5ML competition pool · 33.4kWh U.S. household electricity day · 150L bathtub",
        "",
        'Large activities below 0.01 display "times short" instead of rounding to 0.00.',
        "LED, phone, bottle, kettle, laptop, microwave, pool, and bath use transparent rounded display assumptions.",
        "",
        "Official conversion references:",
        "  EPA WaterSense: 2.0 gal/min ≈ 7.6L/min",
        `  ${WATERSENSE_SOURCE_URL}`,
        "  ENERGY STAR standard dishwasher: 3.2 gal/cycle ≈ 12.1L/cycle",
        `  ${DISHWASHER_SOURCE_URL}`,
        "  EPA average gas car: 3.93×10⁻⁴ metric ton CO₂e/mile ≈ 244.2g/km",
        "  EPA urban tree: 0.060 metric ton CO₂/year",
        "  EPA U.S. home electricity: 12,194kWh/year ≈ 33.4kWh/day",
        `  ${EPA_EQUIVALENCIES_SOURCE_URL}`,
        "",
      ],
    },
    sources: {
      zh: [
        color("1;31", "本地来源统计"),
        "",
        "Codex、Claude Code、OpenCode、OpenClaw 与 Pi 按消息/条目时间精确归因并去重。",
        "Hermes 使用会话或逐模型汇总，按最后活动日归档，因此标为会话级近似。",
        "SQLite 驱动只在对应数据库存在时按需加载；不可用时不影响 JSONL 来源。",
        "扫描 all 时单个来源失败会被标记为未计入，不会遮蔽其他来源。",
        "运行 anti-ai doctor 查看各来源的本地路径、可用性与统计精度。",
        "缺少模型字段统一记为 unknown；不读取或输出会话正文。",
        "",
      ],
      en: [
        color("1;31", "LOCAL SOURCE ACCOUNTING"),
        "",
        "Codex, Claude Code, OpenCode, OpenClaw, and Pi use exact message/entry dates with deduplication.",
        "Hermes uses session or per-model aggregates assigned to the last active day, so it is approximate.",
        "The optional SQLite driver loads only for an existing database; JSONL sources remain available without it.",
        "When scanning all, one failed source is marked not counted instead of hiding healthy sources.",
        "Run anti-ai doctor for each source path, availability, and accounting precision.",
        "Missing model fields become unknown; conversation text is never printed.",
        "",
      ],
    },
    creature: {
      zh: [
        color("1;31", "异变体成长 · 公平玩法"),
        "",
        "每个已结算自然日只增加 1 天阅历，高 Token 不能加速生命阶段。",
        "高用量增加污染性；低用量增加清醒性；AI 清醒日增加 3 点清醒性。",
        "污染与清醒分别保留，可形成污染型、清醒型或矛盾型生态人格。",
        "普通能力每 255 点发生一次恶性增殖；累计点数不会截断，恶性阶会增强对应进化的触发率。",
        "普通事件 12 种、稀有事件 8 种；事件文案变化不会改变原有病理性状选择。",
        "每 14 个阅历日最多出现一个转折病例；污染、清醒、悖论三条路线都有收益与代价。",
        "history 压缩关键节点，prognosis 只给可解释方向，不伪造精确概率。",
        "完整档案使用全部来源；带 --source 的报告不会改写成长史。",
        "状态文件 ~/.anti-ai/creature.json 只保存派生状态和可选外来标本，不保存精确 Token 或对话。",
        "",
      ],
      en: [
        color("1;31", "CREATURE GROWTH · FAIR PLAY"),
        "",
        "Each settled calendar day adds exactly one experience day; Token volume cannot accelerate stages.",
        "High use adds Pollution, low use adds Clarity, and an AI-free day adds 3 Clarity.",
        "Pollution and Clarity persist separately, creating Polluted, Lucid, or Paradox ecologies.",
        "Regular abilities undergo malignant growth every 255 points; lifetime points are never truncated, and each rank strengthens its evolution proc chance.",
        "Twelve common and eight rare events vary the copy without changing the selected pathology trait.",
        "At most one turning-point case appears per 14 experience days; Pollution, Clarity, and Paradox routes each carry a benefit and a cost.",
        "history compresses key events, while prognosis shows explainable directions with no precise probabilities.",
        "The complete file uses all sources; --source reports never rewrite creature history.",
        "~/.anti-ai/creature.json stores derived state and optional foreign specimens, never exact tokens or conversation text.",
        "",
      ],
    },
    privacy: {
      zh: [
        color("1;31", "隐私边界"),
        "",
        "统计在本地完成，不上传原始记录。",
        "成长档案和污染编码只保存用量带/派生外观状态，不保存对话、路径、模型名、精确 Token 或逐请求时间。",
        "codex 和所有 SVG 分享卡都是只读快照；卡片只写入标准输出。",
        "状态迁移会保留原始备份，并拒绝覆盖并发更新或未来 schema。",
        "",
      ],
      en: [
        color("1;31", "PRIVACY BOUNDARY"),
        "",
        "Accounting stays local and raw records are never uploaded.",
        "The creature file and pollution codes store usage bands or derived appearance state, not chats, paths, model names, exact tokens, or request timestamps.",
        "Codex and every SVG card are read-only snapshots; cards are written to stdout only.",
        "State migration keeps an original backup and rejects concurrent overwrites or future schemas.",
        "",
      ],
    },
  };
  return sections[topic][lang].join("\n");
}

function runExplain(lang = "zh", topic = undefined) {
  if (topic) {
    process.stdout.write(focusedExplain(topic, lang));
    return;
  }
  if (lang === "en") {
    const lines = [
      color("1;31", "HOW MUCH PLANET DID YOU AUTOCOMPLETE?"),
      "",
      "Estimated resource use, not a measurement.",
      "Supported local agents do not expose measured per-request resource bills.",
      "This tool calculates named public text-inference cases separately and shows",
      "the highest case for each resource; it is not a statistical range.",
      "",
      color("1", "Google · median Gemini Apps text prompt (2025-05)"),
      "  0.24 Wh · 0.26 mL water · 0.03 gCO₂e / request",
      "  Full-stack production measurement including accelerators, hosts,",
      "  idle capacity, and data-center overhead.",
      `  ${GOOGLE_SOURCE_URL}`,
      "",
      color("1", "OpenAI · average ChatGPT query (2025-06)"),
      "  0.34 Wh · 0.32176 mL water / request",
      "  Official statement without model, prompt-length, or measurement boundary details.",
      `  ${OPENAI_SOURCE_URL}`,
      "",
      color("1", "Mistral · Le Chat / Large 2 lifecycle assessment (2025-07)"),
      "  400 output tokens · 45 mL water · 1.14 gCO₂e",
      "  Includes upstream impacts such as server manufacturing; excludes user devices.",
      `  ${MISTRAL_SOURCE_URL}`,
      "",
      color("1", "Calculations"),
      "  Electricity = max(requests × Google 0.24, requests × OpenAI 0.34)",
      "  Water = max(request-level cases, output tokens ÷ 400 × Mistral 45)",
      "  Carbon = max(requests × Google 0.03, output tokens ÷ 400 × Mistral 1.14)",
      "",
      color("1", "Model attribution"),
      "  Codex: attribute token_count to the latest turn_context.payload.model",
      "         in the same session.",
      "  Claude Code: deduplicate messages by ID, then read assistant message.model.",
      "  OpenCode: read assistant usage from message/session_message in SQLite.",
      "  OpenClaw: deduplicate assistant records across active and reset JSONL files.",
      "  Hermes: prefer per-model SQLite totals; session-level dates remain approximate.",
      "  Pi: count assistant, compaction, and branch-summary usage; deduplicate entry IDs.",
      "  SQLite is optional and lazy-loaded; one failed source cannot hide healthy all-source totals.",
      "  Missing model fields are grouped under unknown. Conversation text is not read or printed.",
      "",
      color("1", "Personal baseline and verdicts"),
      "  Baseline = prior 7 calendar-day total ÷ 7, including days with no records",
      "  The first matching verdict wins:",
      "  CONTEXT HOARDING: requests ≤ 1.2× baseline and tokens/request ≥ 1.8×",
      "  REQUEST BARRAGE: requests ≥ 2× baseline",
      "  CACHE OFFENSE: cached reads are at least 70% of input and at least",
      "                 10 percentage points above the personal baseline",
      "  DIGITAL DETOX: total tokens ≤ 30% of baseline",
      "  COMPUTE BINGE: total tokens ≥ 1.5× baseline",
      "  Otherwise show STEADY BURN; zero usage and missing history have dedicated verdicts.",
      "  Verdicts are generated by fixed local rules; same-category titles and copy",
      "  rotate deterministically by date.",
      "  Each category combines 11 charge titles with 13 detail lines, producing",
      "  143 deterministic combinations before an identical pair repeats.",
      "  Rotation continues across month boundaries and does not reset on day one.",
      "",
      color("1", "Mutation system"),
      "  The first anti-ai creature run backfills the latest 30 calendar days.",
      "  Later runs fill the entire date gap since the previous visit.",
      "  Daily pollution dose = min(100, max(1, round(log10(daily tokens + 1) × 12))).",
      "  Days with no tokens have dose 0.",
      "  Experience grows by 1 for every settled calendar day; high Token use cannot",
      "  accelerate life stages. Stages begin at 1, 7, 30, and 90 experience days.",
      "  Relative to the prior seven-day baseline, high use adds 1–3 POLLUTION;",
      "  low use adds 1–2 CLARITY; an AI-free day adds 3 CLARITY.",
      "  POLLUTION and CLARITY are retained separately, forming UNFORMED, POLLUTED,",
      "  LUCID, or PARADOX ecology. A candidate must persist for 3 settled days",
      "  before the visible ecology changes.",
      "  Branch traits: CONTEXT uses uncached input per request; CACHE uses the",
      "  cached-read share of input; FRENZY uses request count; NUCLEAR is the",
      "  fallback when no specialized trait dominates.",
      "    context += dose × min(1, uncached input ÷ requests ÷ 100,000)",
      "    cache   += dose × min(1, cached reads ÷ total input)",
      "    frenzy  += dose × min(1, requests ÷ 50)",
      "    nuclear += dose × (1 - 0.6 × max(context, cache, frenzy intensity))",
      "  ASCII appearance combines a stable local genome, life stage, usage pathology,",
      "  ecology, achievement parts, and chromatic mutations. The same file is stable;",
      "  different local seeds produce different specimens.",
      "  Twenty-four achievements are split evenly across OFFENSE, SOBRIETY, and PARADOX badges;",
      "  repeatable badges grow through three behavior-based tiers without exact Token totals.",
      "  anti-ai codex derives 50 fixed entries plus private, foreign, fossil, selected case, culture, and companion specimens from schema v10.",
      "  Locked human entries remain ???; JSON exposes stable IDs and discovery dates.",
      "  Seven abilities grow: TOKEN APPETITE, PARASITIC MEMORY, CACHE CARAPACE,",
      "  REQUEST MAWS, CORE GLOW, INSTABILITY, and WITHDRAWAL.",
      "  Visible ability values run from 1–255. Point 256 becomes MALIGNANT I · 1/255;",
      "  lifetime points remain lossless. Active days add 1–2 APPETITE, 1 point to the",
      "  dominant usage ability, a 25% seeded random bonus, and 1 event-linked point.",
      "  INSTABILITY adds 1 percentage point to the rare-mutation chance per 10 points,",
      "  starting at 8% rare mutation chance and capped at 20%.",
      "  Ability values unlock mutation talents at 5, 15, 30, 60, 120, and 220.",
      "  Chromatic abilities awaken independently on active days: R 0.50%, SR 0.10%,",
      "  and SSR 0.02%. Drawing the same one again grows it, up to level 9.",
      "  One event is selected with SHA-256(local seed + date); a base 8% enters the rare pool.",
      "  A common event adds 8 to one trait; a rare event adds 20.",
      "  After the first active day, each AI-free day reduces exposure by 2",
      "  and adds 1 WITHDRAWAL without clearing historical traits.",
      "  Every 90 experience days seal one permanent fossil with that generation's",
      "  ability gains, sealed snapshot, and new malignancy ranks. The next generation",
      "  restarts its four life stages while inheriting one ability and one scar.",
      "  Each new generation offers one POLLUTION, one CLARITY, and one PARADOX choice.",
      "  anti-ai creature evolve <1|2|3> seals the choice; ignoring it never blocks reports.",
      "  Proc chance = min(35%, 5% + min(10, floor(lifetime ability ÷ 25))",
      "  + 2% per unlocked talent + 2% per malignancy rank).",
      "  Higher talent tiers amplify both the benefit and its cost; there is no free upgrade.",
      "  Every 14 experience days may offer at most one turning-point case from 12",
      "  local case skeletons. POLLUTION, CLARITY, and PARADOX choices each seal one",
      "  benefit and one cost; an unanswered case does not build a choice backlog.",
      "  anti-ai creature history compresses stages, mutations, badges, and case choices;",
      "  --full expands privacy-safe daily bands. prognosis previews three explainable",
      "  directions with LEADING/POSSIBLE/LATENT labels, never precise probabilities.",
      "  State: ~/.anti-ai/creature.json (schema v10; schema v1-v9 migrate sequentially",
      "  with an exact local backup and concurrent-write protection).",
      "  It stores only usage bands, derived ecology points, genes/part IDs, achievements,",
      "  fossils, evolution choices, turning-point cases, derived cultures and ingredient",
      "  references, companion bonds/discrete imprints/anomaly IDs, dose, traits,",
      "  ability/chromatic gains, events, and a",
      "  local seed—not chats, paths, model names, exact tokens, or per-request timestamps.",
      "  anti-ai creature reset explicitly destroys this file.",
      "",
      color("1", "Pollution laboratory"),
      "  The lab references saved foreign specimens, permanent fossils, and selected",
      "  case slices. It presents three deterministic formulas for the current batch.",
      "  Incubation does not consume materials and does not change growth, abilities, or ecology.",
      "  Cultures add private collection variety without creating a Token-powered shortcut.",
      "  Use anti-ai lab incubate <1|2|3> only after the user chooses a formula.",
      "  A sealed culture may be bonded as a symbiotic companion. It receives exactly",
      "  one imprint per observed day: heavy, restrained, and AI-free days grow at",
      "  the same rate while shaping POLLUTION, CLARITY, or PARADOX.",
      "  PARASITIC HATCHLING grows into SYMBIOTIC ABERRATION at day 7 and",
      "  ACCOMPLICE ORGAN at day 21; both milestones seal deterministic anomalies.",
      "  Companion growth is narrative and visual only. It changes no creature numbers.",
      "",
      color("1", "Living casebook"),
      "  Complete-source human week reports settle creature history and append the",
      "  primary symptom, Ecology change, stage growth, new badges, and an attending note.",
      "  Complete-source human month reports append a monthly follow-up with post-hatch",
      "  observation totals, Ecology transition, growth, achievements, collections, and a conclusion.",
      "  Complete-source today/week/month reports surface collection discoveries.",
      "  Source-filtered week/month reports stay usage-only and do not alter creature history.",
      "",
      color("1", "Everyday comparisons"),
      "  10W LED light: electricity Wh ÷ 10W = hours lit",
      "  50W laptop: electricity Wh ÷ 50W = hours running",
      "  19Wh phone charge: electricity Wh ÷ 19Wh = charges",
      "  0.05mL water drop and 550mL bottle: water mL ÷ each capacity",
      "  Boil 1L water: electricity Wh ÷ 100Wh = boils",
      "  1kW microwave: electricity Wh ÷ 1,000W = hours running",
      "  WaterSense shower: water mL ÷ 7,600mL/min = minutes",
      "  ENERGY STAR dishwasher: water mL ÷ 12,100mL = cycles",
      "  Month scale also shows a 2.5ML pool, 33.4kWh U.S. household day, and 150L bath.",
      '  Values below 0.01 large activities display "times short" instead of 0.00.',
      "",
      "  Average gas car: US EPA equivalency factor of 244.2 g CO₂e/km",
      "  Driving distance = carbon gCO₂e ÷ 244.2",
      `  ${EPA_EQUIVALENCIES_SOURCE_URL}`,
      "",
      "  Urban tree: US EPA estimate of about 60 kg CO₂/year",
      "  Tree time = carbon gCO₂e ÷ 60,000 × 365 days",
      "  Species, age, and what happens after felling vary too much, so this tool",
      "  reports sequestration time instead of claiming a number of trees cut down.",
      `  ${EPA_EQUIVALENCIES_SOURCE_URL}`,
      "",
      "  U.S. household electricity: EPA 12,194kWh/year ÷ 365 ≈ 33.4kWh/day",
      `  ${EPA_EQUIVALENCIES_SOURCE_URL}`,
      "",
      color("1", "Share card"),
      "  anti-ai share uses the same estimate formulas and fixed local verdict rules.",
      "  anti-ai share --card pathology creates a complete-source mutation pathology card.",
      "  specimen, wanted, fossil, encounter, prognosis, and culture add privacy-safe collection cards.",
      "  codex and every share card are read-only snapshots that never create or advance state.",
      "  creature export and encounter exchange only derived appearance IDs; all mixing stays local.",
      "  The share card omits chats, paths, model names, and exact token counts.",
      "  Every card also omits source names and request counts.",
      "  The SVG is written to stdout and is not uploaded anywhere.",
      "",
      "These named public cases are directional references, not local model telemetry.",
      "",
      color(
        "2",
        "AI is excellent at generating answers. Vendors are still working on utility bills.",
      ),
      "",
    ];
    process.stdout.write(lines.join("\n"));
    return;
  }

  const lines = [
    color("1;31", "HOW MUCH PLANET DID YOU AUTOCOMPLETE?"),
    "",
    "资源消耗估算，不是实际测量值。",
    "受支持的本地 Agent 都没有公开逐请求资源账单。本工具把具名公开案例",
    "分别计算，每项资源只展示数值最高的案例；这不是统计区间。",
    "",
    color("1", "Google · Gemini Apps 中位文本请求（2025-05）"),
    "  0.24 Wh · 0.26 mL 水 · 0.03 gCO₂e / 请求",
    "  生产环境全栈测量，包含加速器、主机、空闲容量和机房开销。",
    `  ${GOOGLE_SOURCE_URL}`,
    "",
    color("1", "OpenAI · 平均 ChatGPT 查询（2025-06）"),
    "  0.34 Wh · 0.32176 mL 水 / 请求",
    "  官方声明，但没有公开模型、请求长度和测量边界。",
    `  ${OPENAI_SOURCE_URL}`,
    "",
    color("1", "Mistral · Le Chat / Large 2 生命周期评估（2025-07）"),
    "  400 输出 tokens · 45 mL 水 · 1.14 gCO₂e",
    "  包含服务器制造等上游影响，不包含用户终端。",
    `  ${MISTRAL_SOURCE_URL}`,
    "",
    color("1", "计算"),
    "  电力 = max(请求数 × Google 0.24, 请求数 × OpenAI 0.34)",
    "  水耗 = max(请求级案例, 输出 tokens ÷ 400 × Mistral 45)",
    "  碳排 = max(请求数 × Google 0.03, 输出 tokens ÷ 400 × Mistral 1.14)",
    "",
    color("1", "模型统计"),
    "  Codex：将 token_count 归属到同一会话中最近的 turn_context.payload.model",
    "  Claude Code：消息按 ID 去重后，读取 assistant message.model",
    "  OpenCode：从 SQLite message/session_message 读取 assistant usage",
    "  OpenClaw：跨活动与 reset JSONL 按消息 ID 去重",
      "  Hermes：优先读取逐模型 SQLite 汇总；日期仍是会话级近似",
      "  Pi：统计 assistant、compaction、branch_summary，并按 entry ID 去重",
      "  SQLite 为可选按需能力；单个来源失败不会遮蔽其他来源的合计。",
    "  缺少模型字段时统一显示 unknown；不读取或输出会话正文。",
    "",
    color("1", "个人基线与判词"),
    "  基线 = 过去 7 个自然日总量 ÷ 7，包含无记录日",
    "  判词按以下顺序命中第一条：",
    "  上下文囤积：请求数不高于基线 1.2 倍，且单次 Token 不低于 1.8 倍",
    "  请求连发：请求数不低于基线 2 倍",
    "  缓存类罪名：缓存读取占输入至少 70%，且高出个人基线至少 10 个百分点",
    "  电子戒断：Token 总量不高于基线 30%",
    "  算力暴食：Token 总量不低于基线 1.5 倍",
    "  其余情况显示“稳定消耗”；无请求或无历史时使用专用判词。",
    "  判词由本地固定规则生成，不调用模型；同类罪名标题和文案按日期固定轮换。",
    "  每类判词由 11 个罪名标题与 13 条详情组合，完整组合有 143 种后才会原样重复。",
    "  跨月轮换不会重置，会连续进入下一组组合。",
    "",
    color("1", "污染进化系统"),
    "  首次运行回看最近 30 个自然日。",
    "  后续运行会补齐两次查看之间的全部日期空档。",
    "  污染剂量 = min(100, max(1, round(log10(当日 Token + 1) × 12)))，每日上限 100。",
    "  当日没有 Token 时污染剂量为 0。",
    "  阅历：每个已结算自然日 +1；高 Token 消耗不能加速生命阶段。",
    "  生命阶段从第 1、7、30、90 个阅历日开始。",
    "  相对过去 7 日基线，高用量增加 1–3 点污染性，低用量增加 1–2 点清醒性，",
    "  AI 清醒日增加 3 点清醒性。",
    "  污染性和清醒性分别保留，形成未定型、污染型、清醒型、矛盾型；",
    "  候选状态需连续 3 个已结算日成立，才会正式改变生态人格。",
    "  上下文病变：非缓存输入的单次平均量；缓存化石：缓存读取占比；",
    "  请求增殖：请求数；核食：没有专门性状占优时的高剂量兜底。",
    "    上下文 += 污染剂量 × min(1, 非缓存输入 ÷ 请求数 ÷ 100,000)",
    "    缓存   += 污染剂量 × min(1, 缓存读取 ÷ 总输入)",
    "    请求   += 污染剂量 × min(1, 请求数 ÷ 50)",
    "    核食   += 污染剂量 × (1 - 0.6 × max(上下文、缓存、请求强度))",
    "  ASCII 外观由稳定本地基因、生命阶段、使用病型、生态人格、成就部件和异色突变共同拼装。",
    "  同一档案稳定生成同一标本，不同本地 seed 尽量生成不同个体。",
    "  首批 24 项成就平均分为罪证章、戒断章、悖论章三类；可重复成就按行为次数成长为三级，",
    "  不使用精确 Token 作为等级条件。anti-ai codex 从 schema v10 派生 50 项固定收藏、动态/外来标本、化石、已封存病例切片、培养物和伴生异物。",
    "  人类输出的锁定项保持 ???，JSON 提供稳定 ID 和发现日期。",
    "  7 个能力值：吞噬欲、赘生脑回、化石甲、请求口器、核素亮度、失控指数、戒断反应。",
    "  普通能力按 255 点循环：第 256 点显示为“恶性 I · 1/255”，累计点数不会截断。",
    "  活跃日获得 1–2 点吞噬欲、1 点主使用能力、25% 确定性随机加点和 1 点事件关联能力。",
    "  失控指数每 10 点让稀有突变率增加 1 个百分点，基础 8%，上限 20%。",
    "  能力值达到 5、15、30、60、120、220 时解锁对应的畸变天赋。",
    "  异色能力在活跃日独立觉醒：R 0.50%、SR 0.10%、SSR 0.02%；重复觉醒同一能力会升级，最高 9 级。",
    "  每日事件由 SHA-256（本地 seed + 日期）确定，基础 8% 进入稀有突变池。",
    "  普通事件给一个性状 +8，稀有事件 +20。",
    "  首个活跃日之后，每个 AI 清醒日污染 -2、戒断反应 +1，但不会清除历史性状。",
    "  每 90 个阅历日封存一枚永久化石，同时记录该代能力增量、封存快照和新增恶性阶；",
    "  下一代重新经历四个生命阶段，继承上一代的一项能力和一道伤疤。",
    "  每代提供污染、清醒、悖论三选一；运行 anti-ai creature evolve <1|2|3> 显式确认，不选择也不会阻断账单。",
    "  触发概率 = min(35%, 5% + min(10, floor(累计能力值 ÷ 25)) + 每项已解锁天赋 2% + 每个恶性阶 2%)。",
    "  高阶天赋会同时放大收益与代价，不存在无成本的最优进化。",
    "  每 14 个阅历日最多出现一个转折病例，从 12 个本地病例骨架中确定性选择。",
    "  污染、清醒、悖论三条路线各有收益与代价；未处理病例不会堆积成待办列表。",
    "  anti-ai creature history 压缩阶段、突变、徽章和病例选择；--full 展开隐私安全的逐日用量带。",
    "  prognosis 使用“主导/可能/潜伏”预演三条可解释方向，不伪造精确概率。",
    "  状态文件：~/.anti-ai/creature.json（schema v10；schema v1-v9 逐版本本地迁移并保留原始备份）",
    "  只保存用量带、派生生态点、基因/部件 ID、成就、化石、进化选择、转折病例、培养物及素材引用、伴生绑定/离散印记/异常 ID、污染剂量、性状、能力与异色加点、事件和本地 seed；",
    "  不保存精确 Token、模型名、路径、对话或逐请求时间。",
    "  anti-ai creature reset 会显式销毁档案。",
    "",
    color("1", "污染实验室"),
    "  实验室只引用已保存的外来标本、永久化石和已选择的病例切片，",
    "  每批给出三份确定性配方。培养不会消耗素材，也不会改变成长、能力或生态。",
    "  培养物只增加私有收藏差异，不提供靠 Token 刷出的升级捷径。",
    "  用户选定配方后，再运行 anti-ai lab incubate <1|2|3>。",
    "  已封存培养物可以绑定为伴生异物。每天只增加一枚印记；高消耗、克制使用和 AI 清醒日",
    "  成长速度相同，但会分别塑造污染、清醒或悖论路线。",
    "  寄生幼体会在第 7 天成为共生异形、第 21 天成为共犯器官；两个里程碑都会封存确定性异常。",
    "  伴生成长只改变叙事和外观，不改变主异变体的任何数值。",
    "",
    color("1", "活体病历"),
    "  完整来源的 week 会结算成长史，追加主症状、生态变化、阶段成长、新徽章和主治意见。",
    "  完整来源的 month 会追加月度复诊，汇总孵化后的有效观察、生态迁移、成长、成就、收藏和结论。",
    "  完整来源的 today/week/month 都会展示对应周期的新增收藏。",
    "  带来源过滤的 week/month 只展示用量，不改动完整成长史。",
    "",
    color("1", "生活化对照"),
    "  10W LED 灯：电力 Wh ÷ 10W = 点灯小时数",
    "  50W 笔记本电脑：电力 Wh ÷ 50W = 使用小时数",
    "  19Wh 手机充电：电力 Wh ÷ 19Wh = 充电次数",
    "  0.05mL 一滴水、550mL 饮用水：水耗 mL ÷ 对应容量",
    "  烧开 1L 水：电力 Wh ÷ 100Wh = 烧水壶数",
    "  1kW 微波炉：电力 Wh ÷ 1,000W = 运行小时数",
    "  WaterSense 淋浴：水耗 mL ÷ 7,600mL/min = 淋浴分钟数",
    "  ENERGY STAR 洗碗机：水耗 mL ÷ 12,100mL = 运行次数",
    "  月度还展示 250 万升泳池、33.4kWh 美国家庭日均用电和 150L 一缸洗澡水。",
    "  大事务不足 0.01 次时显示“还差多少倍”，不会舍入成 0.00。",
    "",
    "  平均燃油车：EPA 等效换算因子 244.2 g CO₂e/公里",
    "  驾车距离 = 碳排 gCO₂e ÷ 244.2",
    `  ${EPA_EQUIVALENCIES_SOURCE_URL}`,
    "",
    "  城市树：EPA 约 60 kg CO₂/年",
    "  树木时间 = 碳排 gCO₂e ÷ 60,000 × 365 天",
    "  树种、树龄和砍伐后的碳去向差异很大，因此不换算成“砍了几棵树”。",
    `  ${EPA_EQUIVALENCIES_SOURCE_URL}`,
    "",
    "  美国家庭用电：EPA 12,194kWh/年 ÷ 365 ≈ 33.4kWh/天",
    `  ${EPA_EQUIVALENCIES_SOURCE_URL}`,
    "",
    color("1", "分享卡片"),
    "  anti-ai share 使用相同的资源估算公式和本地固定判词。",
    "  anti-ai share --card pathology 使用完整成长史生成异变体病理报告。",
    "  specimen、wanted、fossil、encounter、prognosis、culture 提供隐私安全的收藏卡。",
    "  codex 和所有分享卡都是只读快照，不会创建或推进异变体档案。",
    "  creature export 与 encounter 只交换派生外观 ID，全部混合都在本地完成。",
    "  所有卡片都不包含对话、路径、模型名或精确 Token，也不包含来源名和请求数；SVG 只写入标准输出，不会上传。",
    "",
    "这些具名公开案例只提供方向性参照，不是本地模型遥测。",
    "",
    color("2", "AI 很擅长生成答案，厂商还不太擅长生成电费单。"),
    "",
  ];
  process.stdout.write(lines.join("\n"));
}

export { focusedExplain, runExplain };
