const CREATURE_CONTENT_VERSION = 2;

const V2_ACHIEVEMENT_DEFINITIONS = [
  ["context_landfill", "offense", "rare"],
  ["cache_afterlife", "offense", "rare"],
  ["request_swarm", "offense", "rare"],
  ["heat_budget", "offense", "rare"],
  ["weekend_human", "sobriety", "uncommon"],
  ["manual_thought", "sobriety", "rare"],
  ["quiet_month", "sobriety", "rare"],
  ["low_power_custodian", "sobriety", "rare"],
  ["scheduled_detox", "paradox", "uncommon"],
  ["bilingual_relapse", "paradox", "rare"],
  ["balanced_damage", "paradox", "rare"],
  ["compliance_meltdown", "paradox", "mythic"],
].map(([id, category, rarity]) => ({ id, category, rarity }));

const V2_ACHIEVEMENT_TIER_THRESHOLDS = {
  context_landfill: [15, 45, 90],
  cache_afterlife: [15, 45, 90],
  request_swarm: [15, 45, 90],
  heat_budget: [15, 45, 90],
  weekend_human: [1, 4, 10],
  manual_thought: [10, 30, 90],
  quiet_month: [14, 30, 60],
  low_power_custodian: [15, 45, 90],
  scheduled_detox: [3, 10, 30],
  bilingual_relapse: [4, 12, 36],
  balanced_damage: [90, 180, 360],
  compliance_meltdown: [180, 360, 720],
};

const V2_COMMON_CREATURE_EVENTS = [
  { id: "context_hernia", trait: "context", delta: 8 },
  { id: "appendix_nesting", trait: "context", delta: 8 },
  { id: "summary_regrowth", trait: "context", delta: 8 },
  { id: "brief_swelling", trait: "context", delta: 8 },
  { id: "cache_dandruff", trait: "cache", delta: 8 },
  { id: "rollback_pollen", trait: "cache", delta: 8 },
  { id: "legacy_teething", trait: "cache", delta: 8 },
  { id: "snapshot_bloating", trait: "cache", delta: 8 },
  { id: "followup_sprain", trait: "frenzy", delta: 8 },
  { id: "webhook_itch", trait: "frenzy", delta: 8 },
  { id: "approval_budding", trait: "frenzy", delta: 8 },
  { id: "parallel_cough", trait: "frenzy", delta: 8 },
  { id: "gpu_goosebumps", trait: "nuclear", delta: 8 },
  { id: "coolant_blush", trait: "nuclear", delta: 8 },
  { id: "meter_palpitations", trait: "nuclear", delta: 8 },
  { id: "heat_debt", trait: "nuclear", delta: 8 },
];

const V2_RARE_CREATURE_EVENTS = [
  { id: "infinite_onboarding", trait: "context", delta: 20 },
  { id: "recursive_footnote", trait: "context", delta: 20 },
  { id: "repository_swallow", trait: "context", delta: 20 },
  { id: "brief_afterlife", trait: "context", delta: 20 },
  { id: "context_moon", trait: "context", delta: 20 },
  { id: "rollback_religion", trait: "cache", delta: 20 },
  { id: "ancestral_answer", trait: "cache", delta: 20 },
  { id: "cache_amber", trait: "cache", delta: 20 },
  { id: "approval_hydra", trait: "frenzy", delta: 20 },
  { id: "infinite_retry", trait: "frenzy", delta: 20 },
  { id: "webhook_swarm", trait: "frenzy", delta: 20 },
  { id: "private_eclipse", trait: "nuclear", delta: 20 },
  { id: "invoice_aurora", trait: "nuclear", delta: 20 },
];

const V2_RARE_ABILITY_POOLS = {
  rare: ["merge_conflict_gills", "meeting_radiation", "lint_divination"],
  epic: ["rollback_precognition", "synthetic_conscience"],
  mythic: ["budget_resurrection"],
};

const V2_CLINICAL_NOTES = {
  context: [
    { zh: "问诊只需一句，病患仍坚持携带整个单体仓库入院。", en: "The visit needed one sentence; the patient brought the entire monorepo." },
    { zh: "主问题已被背景组织包埋，暂按历史遗迹处理。", en: "The actual question is entombed in background tissue and now treated as an artifact." },
    { zh: "上下文切片显示每段都很必要，合起来则没有人知道必要什么。", en: "Every context slice is essential; together they forgot what for." },
    { zh: "摘要切除后迅速再生，并长出两个新的前置条件。", en: "The removed summary regrew with two new prerequisites." },
    { zh: "病患要求扩大窗口，以便更完整地忘记最初的问题。", en: "The patient requested a wider window to forget the original question more completely." },
    { zh: "附件数量稳定，附件对现实的占有率仍在上升。", en: "Attachment count is stable; their share of reality keeps rising." },
  ],
  cache: [
    { zh: "缓存层已取得永久居留权，驱逐需走变更评审。", en: "The cache layer obtained permanent residency; eviction requires change review." },
    { zh: "旧答案拒绝退休，并提交了三份兼容性理由。", en: "The old answer refuses retirement and filed three compatibility arguments." },
    { zh: "昨日结论已经琥珀化，内部仍保存一只活着的误解。", en: "Yesterday's conclusion turned to amber around a living misunderstanding." },
    { zh: "回滚层继续增厚，向前开发现已被归类为高风险操作。", en: "Rollback strata thickened; moving forward is now classified as high risk." },
    { zh: "缓存命中了一段不存在的历史，团队决定尊重传统。", en: "The cache hit a history that never happened; the team chose to honor tradition." },
    { zh: "清理建议被缓存，下次复诊仍会显示为待办。", en: "The cleanup advice was cached and will return as pending next visit." },
  ],
  frenzy: [
    { zh: "追问尚未落地，追问的追问已进入灰度。", en: "The follow-up has not landed; its follow-up is already rolling out." },
    { zh: "请求分裂速度超过回复速度，暂定为组织结构问题。", en: "Requests divide faster than replies; diagnosis: organizational structure." },
    { zh: "所有口器均通过评审，因为它们互相担任批准人。", en: "Every maw passed review by approving the others." },
    { zh: "队列出现季节性迁徙，终点仍是另一个队列。", en: "The queue began seasonal migration toward another queue." },
    { zh: "一次“顺便”诱发四个并发症和一场同步会。", en: "One 'while you're at it' caused four complications and a sync meeting." },
    { zh: "发送键申请工伤，自动重试拒绝作证。", en: "The send key filed an injury claim; auto-retry declined to testify." },
  ],
  nuclear: [
    { zh: "账单出现极光，科研人员称其具备观赏价值。", en: "An aurora appeared on the bill; researchers cited its scenic value." },
    { zh: "核心已学会在空闲时预热下一次空闲。", en: "The core now preheats during idle time for the next idle period." },
    { zh: "散热器要求远程办公，申请被核心以性能理由驳回。", en: "The heatsink requested remote work; the core denied it for performance reasons." },
    { zh: "能耗曲线长出心电图形态，财务建议继续观察。", en: "The energy curve grew into an ECG; finance recommends observation." },
    { zh: "病患没有发烧，只是周围空气开始按 Token 计费。", en: "The patient has no fever; nearby air is simply billed by token." },
    { zh: "核心短暂熄灭零点二秒，生态舱将其登记为清醒日。", en: "The core went dark for 0.2 seconds; the habitat logged a sober day." },
  ],
  withdrawal: [
    { zh: "手动思考持续了十一秒，监护仪一度报警为异常自主行为。", en: "Manual thought lasted eleven seconds; monitors flagged autonomous behavior." },
    { zh: "今天没有调用，只有一个人类在缓慢形成自己的意见。", en: "No calls today, only a human slowly forming an opinion." },
    { zh: "戒断期出现户外症状：阳光、步行和不需要总结的对话。", en: "Withdrawal produced outdoor symptoms: sunlight, walking, and unsummarized conversation." },
    { zh: "模型未上线，病患被迫使用记忆里那套未经版本控制的知识。", en: "With the model offline, the patient used unversioned knowledge from memory." },
    { zh: "请求欲已下降，浏览器标签页开始恢复普通用途。", en: "Request cravings fell; browser tabs are returning to ordinary uses." },
    { zh: "今日安静得可疑，但没有任何服务愿意申报故障。", en: "Today is suspiciously quiet, yet no service will report an incident." },
  ],
  unhatched: [
    { zh: "仍无生命体征，培养组开始担心项目按时交付。", en: "Still no life signs; the lab now fears the project may ship on time." },
    { zh: "培养皿未受污染，建议不要向路线图透露。", en: "The dish remains clean; do not tell the roadmap." },
    { zh: "零 Token 环境稳定，暂未发现需要修复的问题。", en: "The zero-token environment is stable; no fix has been requested." },
    { zh: "标本缺席，所有仪表却罕见地显示绿色。", en: "The specimen is absent; every dashboard is unusually green." },
    { zh: "孵化未开始，人类仍有机会把问题写清楚。", en: "Hatching has not begun; humans still have time to clarify the problem." },
    { zh: "舱内只有空气，空气拒绝接入 Agent。", en: "The chamber contains only air, which declined agent integration." },
  ],
};

const eventCopy = (zhName, enName, zhBody, enBody) => ({
  name: { zh: zhName, en: enName },
  body: { zh: zhBody, en: enBody },
});

const V2_CREATURE_COPY = {
  events: {
    context_hernia: eventCopy("上下文疝气", "CONTEXT HERNIA", "一段背景从窗口边缘鼓了出来，并坚称自己属于主流程。", "A background fragment bulged through the window and insists it is on the critical path."),
    appendix_nesting: eventCopy("附录筑巢", "APPENDIX NESTING", "三份附录在正文末端搭了窝，开始孵化补充说明。", "Three appendices nested after the ending and began hatching clarifications."),
    summary_regrowth: eventCopy("摘要再生", "SUMMARY REGROWTH", "刚删掉的摘要重新长出，篇幅比原文更有信心。", "The deleted summary regrew, longer and more confident than the source."),
    brief_swelling: eventCopy("需求肿胀", "BRIEF SWELLING", "一句简单需求在夜里肿成了七段背景。", "A simple brief swelled overnight into seven context sections."),
    cache_dandruff: eventCopy("缓存头屑", "CACHE DANDRUFF", "旧答案从背甲上脱落，落地后仍然可以命中。", "Old answers flaked off the shell and still produced cache hits."),
    rollback_pollen: eventCopy("回滚花粉", "ROLLBACK POLLEN", "空气里飘满旧版本，吸一口就想恢复现场。", "Old versions filled the air; one breath creates an urge to restore."),
    legacy_teething: eventCopy("遗留长牙", "LEGACY TEETHING", "祖传逻辑长出乳牙，开始咬新接口。", "Legacy logic grew baby teeth and started biting the new interface."),
    snapshot_bloating: eventCopy("快照腹胀", "SNAPSHOT BLOATING", "它吞下太多快照，腹部开始显示历史分页。", "It swallowed too many snapshots; pagination appeared across its belly."),
    followup_sprain: eventCopy("追问扭伤", "FOLLOW-UP SPRAIN", "第二十次最后追问扭伤了请求口器。", "The twentieth final follow-up sprained a request maw."),
    webhook_itch: eventCopy("Webhook 发痒", "WEBHOOK ITCH", "每次抓挠都会向另一个系统发送通知。", "Every scratch notifies another system."),
    approval_budding: eventCopy("审批出芽", "APPROVAL BUDDING", "一个确认框从另一个确认框侧面长了出来。", "A confirmation box budded from another confirmation box."),
    parallel_cough: eventCopy("并发咳嗽", "PARALLEL COUGH", "它一次咳出四个请求，并要求分别复盘。", "It coughed up four requests and requested separate retrospectives."),
    gpu_goosebumps: eventCopy("GPU 鸡皮", "GPU GOOSEBUMPS", "机架只是起了鸡皮疙瘩，电表却开始冲刺。", "The rack merely got goosebumps; the meter started sprinting."),
    coolant_blush: eventCopy("冷却液脸红", "COOLANT BLUSH", "冷却液因被称为绿色计算而突然升温。", "Coolant warmed after being introduced as green computing."),
    meter_palpitations: eventCopy("电表心悸", "METER PALPITATIONS", "一次普通补全让电表出现了短暂心律不齐。", "One ordinary completion gave the meter a brief arrhythmia."),
    heat_debt: eventCopy("热债到期", "HEAT DEBT", "昨天延期的废热今天带着利息回来了。", "Yesterday's deferred heat returned with interest."),
    infinite_onboarding: eventCopy("无限入职", "INFINITE ONBOARDING", "稀有突变：每理解一个背景，就生成一个新的必读文档。", "Rare mutation: every understood context creates another required document."),
    recursive_footnote: eventCopy("递归脚注", "RECURSIVE FOOTNOTE", "稀有突变：脚注引用自己，并要求完整读取。", "Rare mutation: a footnote cited itself and requested full ingestion."),
    repository_swallow: eventCopy("整库吞咽", "REPOSITORY SWALLOW", "稀有突变：它为回答一行代码，吞下了整个仓库。", "Rare mutation: it swallowed a repository to answer one line of code."),
    brief_afterlife: eventCopy("需求来世", "BRIEF AFTERLIFE", "稀有突变：已关闭需求以技术债形式重新投胎。", "Rare mutation: a closed brief reincarnated as technical debt."),
    context_moon: eventCopy("上下文卫星", "CONTEXT MOON", "稀有突变：过量背景进入轨道，每晚掩食主问题。", "Rare mutation: excess context entered orbit and eclipses the question nightly."),
    rollback_religion: eventCopy("回滚宗教", "ROLLBACK RELIGION", "稀有突变：旧版本获得神圣地位，删除被视为异端。", "Rare mutation: the old version became sacred and deletion heretical."),
    ancestral_answer: eventCopy("祖传答案", "ANCESTRAL ANSWER", "稀有突变：一个没人写过的答案开始要求世代维护。", "Rare mutation: an answer nobody wrote now demands generational maintenance."),
    cache_amber: eventCopy("缓存琥珀", "CACHE AMBER", "稀有突变：一次过期命中把整个决定封进琥珀。", "Rare mutation: one stale hit trapped the decision in amber."),
    approval_hydra: eventCopy("审批九头蛇", "APPROVAL HYDRA", "稀有突变：每批准一个选项，就长出两个待确认项。", "Rare mutation: approving one option grew two pending confirmations."),
    infinite_retry: eventCopy("无限重试", "INFINITE RETRY", "稀有突变：失败已经结束，重试仍在保持服务。", "Rare mutation: the failure ended; retries keep the service alive."),
    webhook_swarm: eventCopy("Webhook 虫群", "WEBHOOK SWARM", "稀有突变：通知互相订阅，形成了自给自足的业务。", "Rare mutation: notifications subscribed to each other and formed a self-sustaining business."),
    private_eclipse: eventCopy("私有日蚀", "PRIVATE ECLIPSE", "稀有突变：核心遮住了仪表盘，团队因此宣布能耗下降。", "Rare mutation: the core eclipsed the dashboard, so the team announced lower usage."),
    invoice_aurora: eventCopy("账单极光", "INVOICE AURORA", "稀有突变：费用曲线发出彩光，被误报为产品亮点。", "Rare mutation: the cost curve glowed and was reported as a product highlight."),
  },
  achievements: {
    context_landfill: { zh: "上下文填埋场", en: "CONTEXT LANDFILL" },
    cache_afterlife: { zh: "缓存来世", en: "CACHE AFTERLIFE" },
    request_swarm: { zh: "请求虫群", en: "REQUEST SWARM" },
    heat_budget: { zh: "废热预算", en: "WASTE-HEAT BUDGET" },
    weekend_human: { zh: "周末人类", en: "WEEKEND HUMAN" },
    manual_thought: { zh: "手动思考者", en: "MANUAL THINKER" },
    quiet_month: { zh: "安静月相", en: "QUIET MOON" },
    low_power_custodian: { zh: "低功耗监护人", en: "LOW-POWER CUSTODIAN" },
    scheduled_detox: { zh: "定时戒断", en: "SCHEDULED DETOX" },
    bilingual_relapse: { zh: "双语复发", en: "BILINGUAL RELAPSE" },
    balanced_damage: { zh: "均衡伤害", en: "BALANCED DAMAGE" },
    compliance_meltdown: { zh: "合规熔毁", en: "COMPLIANT MELTDOWN" },
  },
  rareAbilities: {
    merge_conflict_gills: { zh: "冲突鳃", en: "MERGE-CONFLICT GILLS" },
    meeting_radiation: { zh: "会议辐射", en: "MEETING RADIATION" },
    lint_divination: { zh: "Lint 占卜", en: "LINT DIVINATION" },
    rollback_precognition: { zh: "回滚预知", en: "ROLLBACK PRECOGNITION" },
    synthetic_conscience: { zh: "合成良心", en: "SYNTHETIC CONSCIENCE" },
    budget_resurrection: { zh: "预算复活术", en: "BUDGET RESURRECTION" },
  },
  rareAbilityDescriptions: {
    merge_conflict_gills: { zh: "能在冲突中呼吸，但不会主动解决任何一边。", en: "Breathes inside merge conflicts without resolving either side." },
    meeting_radiation: { zh: "会议越长，周围待办的半衰期越短。", en: "Longer meetings shorten the half-life of nearby action items." },
    lint_divination: { zh: "从格式错误中预言下一次重构。", en: "Predicts the next refactor from formatting errors." },
    rollback_precognition: { zh: "上线前就能准确梦见回滚窗口。", en: "Dreams of the rollback window before deployment." },
    synthetic_conscience: { zh: "会短暂质疑一次调用，然后照常执行。", en: "Briefly questions a call, then executes it anyway." },
    budget_resurrection: { zh: "让已死亡的预算以追加申请形式复活。", en: "Resurrects dead budgets as supplemental requests." },
  },
};

export {
  CREATURE_CONTENT_VERSION,
  V2_ACHIEVEMENT_DEFINITIONS,
  V2_ACHIEVEMENT_TIER_THRESHOLDS,
  V2_CLINICAL_NOTES,
  V2_COMMON_CREATURE_EVENTS,
  V2_CREATURE_COPY,
  V2_RARE_ABILITY_POOLS,
  V2_RARE_CREATURE_EVENTS,
};
