import {
  mkdir,
  readFile,
  readdir,
  writeFile,
} from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

const projectRoot = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
);
const outputDirectory = path.join(projectRoot, "dist");
const output = path.join(outputDirectory, "tui.mjs");
const noticesOutput = path.join(outputDirectory, "THIRD_PARTY_NOTICES.txt");
const optionalDevtoolsStub = {
  name: "optional-react-devtools-stub",
  setup(builder) {
    builder.onResolve(
      { filter: /^react-devtools-core$/ },
      () => ({ path: "react-devtools-core", namespace: "anti-ai-stub" }),
    );
    builder.onLoad(
      { filter: /.*/, namespace: "anti-ai-stub" },
      () => ({
        contents:
          "export default { initialize() {}, connectToDevTools() {} };",
        loader: "js",
      }),
    );
  },
};

await mkdir(outputDirectory, { recursive: true });
const result = await build({
  entryPoints: [path.join(projectRoot, "src", "tui", "runtime.jsx")],
  outfile: output,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  minify: true,
  legalComments: "eof",
  sourcemap: false,
  metafile: true,
  plugins: [optionalDevtoolsStub],
  define: {
    "process.env.NODE_ENV": '"production"',
  },
  banner: {
    js: [
      "// Generated by scripts/build-tui.mjs. Do not edit directly.",
      'import { createRequire as __antiAiCreateRequire } from "node:module";',
      "const require = __antiAiCreateRequire(import.meta.url);",
    ].join("\n"),
  },
});

const bytes = Object.values(result.metafile.outputs).reduce(
  (sum, entry) => sum + entry.bytes,
  0,
);
const packageRoots = new Set();
for (const input of Object.keys(result.metafile.inputs)) {
  const segments = input.split("/");
  const nodeModulesIndex = segments.lastIndexOf("node_modules");
  if (nodeModulesIndex === -1) continue;
  const packageLength = segments[nodeModulesIndex + 1]?.startsWith("@") ? 2 : 1;
  packageRoots.add(
    segments
      .slice(0, nodeModulesIndex + 1 + packageLength)
      .join(path.sep),
  );
}

const notices = [];
for (const packageRoot of [...packageRoots].sort()) {
  const absoluteRoot = path.resolve(projectRoot, packageRoot);
  const metadata = JSON.parse(
    await readFile(path.join(absoluteRoot, "package.json"), "utf8"),
  );
  const licenseFile = (await readdir(absoluteRoot))
    .sort()
    .find((name) => /^(?:licen[cs]e|copying|notice)(?:\..*)?$/i.test(name));
  const licenseText = licenseFile
    ? (await readFile(path.join(absoluteRoot, licenseFile), "utf8")).trim()
    : `Package metadata declares license: ${String(metadata.license ?? "UNKNOWN")}`;
  notices.push(
    [
      `${metadata.name}@${metadata.version}`,
      `Declared license: ${String(metadata.license ?? "UNKNOWN")}`,
      "",
      licenseText,
    ].join("\n"),
  );
}
await writeFile(
  noticesOutput,
  [
    "THIRD-PARTY NOTICES FOR ANTI-AI TUI",
    "",
    "The following packages are bundled into dist/tui.mjs.",
    "",
    ...notices.flatMap((notice) => [notice, "", "=".repeat(72), ""]),
  ].join("\n"),
);

process.stdout.write(
  `Built ${path.relative(projectRoot, output)} (${Math.ceil(bytes / 1024)} KiB) with ${notices.length} third-party notices.\n`,
);
