const PERIOD_FOOTERS = {
  today: {
    zh: [
      "机器开了小票，地球只收到一段估算。",
      "代码也许省了十分钟，机房没有因此获得年假。",
      "本次灵感已结算，散热风扇拒绝发表感言。",
      "你关闭了终端，账单仍在后台保持清醒。",
      "答案已经复制，热量暂不支持撤销。",
      "模型说不客气，电表说下次记得客气。",
      "今天的效率故事，数据中心拥有另一个版本。",
      "你得到了一段文本，机房得到了一段高温。",
      "这不是碳审判，只是一张不太会夸人的小票。",
      "Token 已经走远，估算还在门口等你签收。",
      "提示词结束了，资源脚注刚刚开始。",
      "人工智能完成了工作，人工开始阅读账单。",
      "快捷键已经松开，电子仍在回忆刚才的奔跑。",
      "结果保存成功，良心缓存命中失败。",
      "今天的答案很轻，送它来的基础设施不这么认为。",
      "你省下一次搜索，怪兽得到一份加餐。",
      "终端显示完成，生态舱显示继续观察。",
      "本次调用没有受害者，只有若干未出席的电子。",
      "灵感来得突然，资源换算来得更有凭据。",
      "模型完成补全，电表完成自己的续写。",
      "你只问了一下，机房也只热了一下又一下。",
      "提示词很简短，它的生命周期分析并不配合。",
      "今日产出已提交，副作用进入本地收藏。",
      "效率没有罪，只是今天又留下了指纹。",
    ],
    en: [
      "The machine printed a receipt. Earth got an estimate.",
      "The code may have saved ten minutes. The server room got no holiday.",
      "Inspiration settled. The cooling fans declined comment.",
      "You closed the terminal. The bill stayed awake.",
      "The answer was copied. The heat has no undo button.",
      "The model said you're welcome. The meter asked for manners.",
      "Your efficiency story has a datacenter edition.",
      "You got text. The server room got temperature.",
      "Not a carbon trial—just a receipt bad at compliments.",
      "The tokens left. Their estimate is waiting for a signature.",
      "The prompt ended. The resource footnote just began.",
      "Artificial intelligence worked. Human intelligence reads the bill.",
      "The shortcut is released. The electrons remember the sprint.",
      "Result saved. Conscience cache miss.",
      "Today's answer was light. The infrastructure carrying it disagrees.",
      "You saved a search. The creature received a snack.",
      "The terminal says done. The habitat says keep observing.",
      "No victims in this call, only several absent electrons.",
      "Inspiration arrived suddenly. The resource conversion brought citations.",
      "The model completed your text. The meter wrote a sequel.",
      "You only asked once. The server room only warmed again and again.",
      "The prompt was short. Its lifecycle analysis was not.",
      "Output committed. Side effects entered the local collection.",
      "Efficiency is not guilty. It merely left another fingerprint.",
    ],
  },
  week: {
    zh: [
      "七天过去了。代码也许能跑，账单肯定能。",
      "本周提交已合并，机房余热仍有冲突。",
      "你修掉了几个 Bug，又成功制造了一张资源周报。",
      "七日算力已封存，周末是否清醒另案处理。",
      "本周效率显著，电表拒绝参与绩效互评。",
      "代码进入主分支，热量进入公共领域。",
      "一周的灵感排成了图表，散热风扇排成了夜班。",
      "你把需求拆成任务，模型把任务拆成请求。",
      "本周没有赢家，只有能运行的代码和能累计的 Token。",
      "周报写完了，数据中心要求补充它的加班记录。",
      "七天的自动补全，浓缩成一段不能报销的脚注。",
      "你完成了迭代，怪兽完成了进食。",
      "本周生产力已到账，副作用正在月结。",
      "下周可以继续优化，电表已经创建了循环任务。",
      "本周少问的那些问题，也成功进入了成长记录。",
      "七天里既有增殖也有克制，怪兽称之为混合喂养。",
      "周曲线已经封存，解释权归生态舱所有。",
      "你完成了冲刺，Token 完成了耐力测试。",
      "提交历史很完整，清醒时段也终于有了姓名。",
      "本周没有刷量奖励，只有更诚实的病理变化。",
      "模型替你节省时间，周报负责把时间重新花掉。",
      "七日账单已出，怪兽拒绝提供发票抬头。",
      "本周工作有了结果，副作用有了路线。",
      "下周继续之前，先让散热器拥有一个周末。",
    ],
    en: [
      "Seven days passed. The code might run; the bill definitely does.",
      "This week's commits merged. Server-room heat still has conflicts.",
      "You fixed bugs and successfully created a resource report.",
      "Seven days of compute archived. Weekend sobriety is a separate case.",
      "Productivity rose. The meter declined peer review.",
      "Code entered main. Heat entered the public domain.",
      "Ideas became charts. Cooling fans got the night shift.",
      "You split requirements into tasks; the model split tasks into requests.",
      "No winner this week—only runnable code and countable tokens.",
      "The report is done. The datacenter submitted overtime.",
      "A week of autocomplete became one non-reimbursable footnote.",
      "You completed an iteration. The creature completed a meal.",
      "Productivity arrived. Side effects invoice monthly.",
      "Optimize again next week. The meter made it recurring.",
      "Questions you did not ask also entered the growth record.",
      "The week mixed proliferation and restraint; the creature calls it mixed feeding.",
      "The weekly curve is sealed. Interpretation belongs to the habitat.",
      "You finished the sprint. Tokens finished an endurance test.",
      "Commit history is complete. Quiet hours finally have a name.",
      "No volume-farming rewards this week, only more honest pathology.",
      "The model saved time. The weekly report spent it again.",
      "The seven-day bill arrived. The creature declined an invoice title.",
      "Work found an outcome. Side effects found a route.",
      "Before next week, let the heatsink have a weekend.",
    ],
  },
  month: {
    zh: [
      "这个月还没结束，数据中心已经替你记住了。",
      "月历翻页了，缓存坚持自己属于文化遗产。",
      "三十天的效率装进一页，余热装不进去。",
      "本月代码可以归档，怪兽申请继续观察。",
      "你完成了月度目标，电表完成了月度增长。",
      "月结不是审判，只是数字终于排队作证。",
      "这个月留下了提交、账单，以及一只更难解释的怪兽。",
      "需求已经复盘，资源脚注拒绝被归为其他。",
      "一个月的提示词结束，长期副作用刚进入试用期。",
      "月度曲线很漂亮，前提是别问纵轴是什么。",
      "本月产出已汇总，清醒日仍然不支持补签。",
      "你把工作做成了历史，缓存把历史做成了地层。",
      "月底到了，模型请求开始假装互不认识。",
      "下个月一切可以重来，派生病历不会。",
      "三十天塑造的不是等级，是一套越来越具体的坏习惯。",
      "本月既喂出器官，也养出几段值得保留的沉默。",
      "月度收藏增加了，产品路线仍然拒绝变成刷量游戏。",
      "这个月的怪兽更像你了，建议双方都做一次复盘。",
      "Token 曲线会归零，世代伤痕坚持跨月结转。",
      "月底病历显示：工作完成，病理继续。",
      "月报能够压缩三十天，不能压缩它们留下的生态。",
      "你获得了产出、收藏和一份越来越难解释的共同生活。",
      "本月清醒不是空白，而是另一条完整成长路线。",
      "下次打开终端时，这只怪兽会记得你如何使用自由。",
    ],
    en: [
      "The month is not over. The datacenter already remembers it.",
      "The calendar turned. Cache insists it is cultural heritage.",
      "Thirty days fit on one page. The waste heat did not.",
      "The code can be archived. The creature remains under observation.",
      "You hit monthly goals. The meter hit monthly growth.",
      "Month-end is not judgment; the numbers finally lined up to testify.",
      "The month left commits, a bill, and a harder-to-explain creature.",
      "Requirements were reviewed. The resource footnote refused 'other'.",
      "A month of prompts ended. Long-term side effects began probation.",
      "The curve looks lovely if nobody asks about the vertical axis.",
      "Output summarized. AI-free days do not accept late check-ins.",
      "You made work history. Cache made history geological.",
      "Month-end arrived. Model requests pretend not to know each other.",
      "Next month can restart. The derived casebook cannot.",
      "Thirty days built no level, only a more specific set of bad habits.",
      "The month grew organs and preserved several useful silences.",
      "The collection expanded. The product still refuses to reward volume farming.",
      "The creature resembles you more this month. Both should run a retrospective.",
      "Token curves reset. Generation scars carry forward.",
      "Month-end diagnosis: work completed, pathology ongoing.",
      "A report compresses thirty days, not the ecology they left behind.",
      "You gained output, collections, and a harder-to-explain cohabitation.",
      "Sobriety was not blank space this month; it was a complete growth route.",
      "Next time the terminal opens, the creature will remember how you used freedom.",
    ],
  },
};

const SHARE_METHODOLOGY = {
  zh: [
    "公开高位参照 · 不是模型级实际测量",
    "公开案例换算 · 不是你这次请求的实测账单",
    "高位生活翻译 · 请勿冒充实验室读数",
    "公开数据参照 · 精确到能讽刺，没精确到能报税",
    "估算负责提醒 · 不负责给模型做碳体检",
    "具名公开案例 · 本地日志只提供 Token 元数据",
    "资源代理值 · 没有读取你的对话正文",
    "高位估算口径 · 现实机房不会寄来同款小票",
    "生活类比用于直觉 · 不是逐请求遥测",
    "Token 换算资源 · 方向认真，数字保持谦虚",
    "公开参照已署名 · 本地模型能耗仍然未知",
    "这是一面讽刺镜 · 不是一台实验室仪器",
    "公开代理值 · 适合形成直觉，不适合形成碳发票",
    "生命周期高位案例 · 有意向保守方向取值",
    "本地只读统计 · 不上传 Token 元数据或成长档案",
    "同一换算口径 · today、week 与 month 不各讲一套故事",
    "资源数字保留边界 · 讽刺文案不冒充科学结论",
    "没有逐模型遥测 · 具体硬件、地区与负载仍会改变结果",
    "比较项取较直观一侧 · 方便理解，不制造虚假精度",
    "方法说明可复核 · 怪兽意见不构成环境审计",
  ],
  en: [
    "Named high-side reference · not a model-level measurement",
    "Public-case conversion · not your request's measured bill",
    "High-side translation · please do not impersonate telemetry",
    "Public reference · precise enough for satire, not taxes",
    "An estimate for reflection, not a model carbon physical",
    "Named public cases · local logs provide token metadata only",
    "Resource proxy · conversation text was never read",
    "High-side method · real datacenters do not mail this receipt",
    "Everyday intuition · not per-request telemetry",
    "Tokens into resources · serious direction, humble numbers",
    "Public cases named · local model energy remains unknown",
    "A satirical mirror, not a laboratory instrument",
    "Public proxy · useful for intuition, not a carbon invoice",
    "High-side lifecycle cases · deliberately conservative in direction",
    "Local read-only accounting · no token metadata or growth state uploaded",
    "One conversion method · today, week, and month tell the same story",
    "Resource numbers keep boundaries · satire does not impersonate science",
    "No per-model telemetry · hardware, region, and load still change outcomes",
    "Comparisons favor legibility · useful intuition without false precision",
    "Method remains inspectable · creature opinions are not an environmental audit",
  ],
};

export { PERIOD_FOOTERS, SHARE_METHODOLOGY };
