const PERIOD_FOOTERS = {
  today: {
    zh: [
      "机器开了小票，地球只收到一段估算。",
      "代码也许省了十分钟，机房没有因此获得年假。",
      "本次灵感已结算，散热风扇拒绝发表感言。",
      "你关闭了终端，账单仍在后台保持清醒。",
      "答案已经复制，热量暂不支持撤销。",
      "模型说不客气，电表说下次记得客气。",
      "今天的效率故事，数据中心拥有另一个版本。",
      "你得到了一段文本，机房得到了一段高温。",
      "这不是碳审判，只是一张不太会夸人的小票。",
      "Token 已经走远，估算还在门口等你签收。",
      "提示词结束了，资源脚注刚刚开始。",
      "人工智能完成了工作，人工开始阅读账单。",
      "快捷键已经松开，电子仍在回忆刚才的奔跑。",
      "结果保存成功，良心缓存命中失败。",
    ],
    en: [
      "The machine printed a receipt. Earth got an estimate.",
      "The code may have saved ten minutes. The server room got no holiday.",
      "Inspiration settled. The cooling fans declined comment.",
      "You closed the terminal. The bill stayed awake.",
      "The answer was copied. The heat has no undo button.",
      "The model said you're welcome. The meter asked for manners.",
      "Your efficiency story has a datacenter edition.",
      "You got text. The server room got temperature.",
      "Not a carbon trial—just a receipt bad at compliments.",
      "The tokens left. Their estimate is waiting for a signature.",
      "The prompt ended. The resource footnote just began.",
      "Artificial intelligence worked. Human intelligence reads the bill.",
      "The shortcut is released. The electrons remember the sprint.",
      "Result saved. Conscience cache miss.",
    ],
  },
  week: {
    zh: [
      "七天过去了。代码也许能跑，账单肯定能。",
      "本周提交已合并，机房余热仍有冲突。",
      "你修掉了几个 Bug，又成功制造了一张资源周报。",
      "七日算力已封存，周末是否清醒另案处理。",
      "本周效率显著，电表拒绝参与绩效互评。",
      "代码进入主分支，热量进入公共领域。",
      "一周的灵感排成了图表，散热风扇排成了夜班。",
      "你把需求拆成任务，模型把任务拆成请求。",
      "本周没有赢家，只有能运行的代码和能累计的 Token。",
      "周报写完了，数据中心要求补充它的加班记录。",
      "七天的自动补全，浓缩成一段不能报销的脚注。",
      "你完成了迭代，怪兽完成了进食。",
      "本周生产力已到账，副作用正在月结。",
      "下周可以继续优化，电表已经创建了循环任务。",
    ],
    en: [
      "Seven days passed. The code might run; the bill definitely does.",
      "This week's commits merged. Server-room heat still has conflicts.",
      "You fixed bugs and successfully created a resource report.",
      "Seven days of compute archived. Weekend sobriety is a separate case.",
      "Productivity rose. The meter declined peer review.",
      "Code entered main. Heat entered the public domain.",
      "Ideas became charts. Cooling fans got the night shift.",
      "You split requirements into tasks; the model split tasks into requests.",
      "No winner this week—only runnable code and countable tokens.",
      "The report is done. The datacenter submitted overtime.",
      "A week of autocomplete became one non-reimbursable footnote.",
      "You completed an iteration. The creature completed a meal.",
      "Productivity arrived. Side effects invoice monthly.",
      "Optimize again next week. The meter made it recurring.",
    ],
  },
  month: {
    zh: [
      "这个月还没结束，数据中心已经替你记住了。",
      "月历翻页了，缓存坚持自己属于文化遗产。",
      "三十天的效率装进一页，余热装不进去。",
      "本月代码可以归档，怪兽申请继续观察。",
      "你完成了月度目标，电表完成了月度增长。",
      "月结不是审判，只是数字终于排队作证。",
      "这个月留下了提交、账单，以及一只更难解释的怪兽。",
      "需求已经复盘，资源脚注拒绝被归为其他。",
      "一个月的提示词结束，长期副作用刚进入试用期。",
      "月度曲线很漂亮，前提是别问纵轴是什么。",
      "本月产出已汇总，清醒日仍然不支持补签。",
      "你把工作做成了历史，缓存把历史做成了地层。",
      "月底到了，模型请求开始假装互不认识。",
      "下个月一切可以重来，派生病历不会。",
    ],
    en: [
      "The month is not over. The datacenter already remembers it.",
      "The calendar turned. Cache insists it is cultural heritage.",
      "Thirty days fit on one page. The waste heat did not.",
      "The code can be archived. The creature remains under observation.",
      "You hit monthly goals. The meter hit monthly growth.",
      "Month-end is not judgment; the numbers finally lined up to testify.",
      "The month left commits, a bill, and a harder-to-explain creature.",
      "Requirements were reviewed. The resource footnote refused 'other'.",
      "A month of prompts ended. Long-term side effects began probation.",
      "The curve looks lovely if nobody asks about the vertical axis.",
      "Output summarized. AI-free days do not accept late check-ins.",
      "You made work history. Cache made history geological.",
      "Month-end arrived. Model requests pretend not to know each other.",
      "Next month can restart. The derived casebook cannot.",
    ],
  },
};

const SHARE_METHODOLOGY = {
  zh: [
    "公开高位参照 · 不是模型级实际测量",
    "公开案例换算 · 不是你这次请求的实测账单",
    "高位生活翻译 · 请勿冒充实验室读数",
    "公开数据参照 · 精确到能讽刺，没精确到能报税",
    "估算负责提醒 · 不负责给模型做碳体检",
    "具名公开案例 · 本地日志只提供 Token 元数据",
    "资源代理值 · 没有读取你的对话正文",
    "高位估算口径 · 现实机房不会寄来同款小票",
    "生活类比用于直觉 · 不是逐请求遥测",
    "Token 换算资源 · 方向认真，数字保持谦虚",
    "公开参照已署名 · 本地模型能耗仍然未知",
    "这是一面讽刺镜 · 不是一台实验室仪器",
  ],
  en: [
    "Named high-side reference · not a model-level measurement",
    "Public-case conversion · not your request's measured bill",
    "High-side translation · please do not impersonate telemetry",
    "Public reference · precise enough for satire, not taxes",
    "An estimate for reflection, not a model carbon physical",
    "Named public cases · local logs provide token metadata only",
    "Resource proxy · conversation text was never read",
    "High-side method · real datacenters do not mail this receipt",
    "Everyday intuition · not per-request telemetry",
    "Tokens into resources · serious direction, humble numbers",
    "Public cases named · local model energy remains unknown",
    "A satirical mirror, not a laboratory instrument",
  ],
};

export { PERIOD_FOOTERS, SHARE_METHODOLOGY };
